version: "3.3"
services:
  vue-ui:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - /shared_file/labs/lab2:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules

